[package]
name = "bevy_extension"
version = "0.1.0"
edition = "2024"

[lib]
path = "src/lib.rs"

[dependencies]
sunray = { path = ".." }
bevy = { path = "../../bevy", default-features = false, features = [
    "async_executor",
    "bevy_log",
    "bevy_window",
    "bevy_winit",
    "std",
] }
ash = { version = "0.38.0", features = ["linked"] }
raw-window-handle = "0.6"
nalgebra = "0.34"
log = "0.4"
parking_lot = "0.12"
rand = "0.10.1"

[dev-dependencies]
log4rs = "1.4"

[[example]]
name = "window"
path = "examples/window.rs"
